import {
  formatFieldDisplayValue,
  formatInvoiceFieldLabel,
  formatMissingLabel,
  INVOICE_FIELDS,
  isMissingField,
  maxInvoiceFieldLabelWidth,
} from "@/lib/invoiceFields";
import type { InvoiceAnalysisResult } from "@/lib/types/invoice";

export function formatInvoiceResultAsText(result: InvoiceAnalysisResult): string {
  const lines: string[] = [
    "InvoiceMind — Invoice extraction summary",
    `Format detected: ${result.detectedFormat || "Unknown"}`,
    "",
  ];

  const labelWidth = maxInvoiceFieldLabelWidth();

  for (const { key, label } of INVOICE_FIELDS) {
    const missing = isMissingField(result.missingFields, key, label);
    const value = formatFieldDisplayValue(
      result[key] as string | number,
      missing
    );
    const fieldLabel = formatInvoiceFieldLabel(label, missing, labelWidth);
    lines.push(`  ${fieldLabel}  ${value}`);
  }

  if (result.missingFields.length > 0) {
    lines.push("", "Missing fields");
    for (const field of result.missingFields) {
      lines.push(`• ${formatMissingLabel(field)}`);
    }
  }

  if (result.warnings.length > 0) {
    lines.push("", "Warnings");
    for (const warning of result.warnings) {
      lines.push(`• ${warning}`);
    }
  }

  lines.push("", "—", "Generated by InvoiceMind");

  return lines.join("\n");
}
